Repository ES2-UFPI/AjudaAi, pull requests merged in 2023-03, with the labels that each got.

#75 Pagina marromeno de filtro de pesquisa Andisu07#69
  templates/filtro_busca.html
Labels: enhancement

#80 Let0210#78
  .github/workflows/actions.yml
  templates/tests/Teste para CadastrarDuvida.html.side
Labels: Tests

#82 Teste de get usuario com swagger jaovctr#77
  API/AjudaAiAPI/Testes/GetUsuario.json
Labels: Tests

#83 Caiofeitosa7#42
  facade.py
  model.py
  notifica.py
  static/estilos_index.css
  static/img/forum.png
  static/styleCadastrarDuvida.css
  static/styleTopicoForum.css
  templates/CadastrarDuvida.html
  templates/Forum.html
  templates/index.html
  templates/topicoForum.html
  views.py
Labels: enhancement

#85 Update and rename Teste para CadastrarDuvida.html.side to PreencherDu…
  templates/tests/PreencherDuvida.py
  templates/tests/Teste para CadastrarDuvida.html.side
Labels: bug

#89 Fix do projeto Andisu07#88
  facade.py
  model.py
  static/styleTopicoForum.css
  templates/CadastrarDuvida.html
  templates/Forum.html
  templates/topicoForum.html
Labels: bug

#104 scripts atualizados Andisu07#97
  BD/Diagrama ER AjudaAi.mwb
  BD/Diagrama ER AjudaAi.mwb.bak
Labels: enhancement

#106 imagem do banco Andisu07#105
  BD/Diagrama 2.2.png
Labels: bug

#107 Let0210#91
  static/styleChatPrivado.css
  templates/ChatPrivado.html
Labels: enhancement

#110 Coelhomca#109
  .vscode/launch.json
  static/style.css
  templates/tests/teste-cadastro-demanda.side
  templates/visualizar_demanda.html
Labels: bug

#108 atualizando o script jaovctr#98
  BD/Script.sql
Labels: enhancement

#112 Adicionando a tela do rank #95
  static/img/estrela.png
  static/img/icon3.png
  static/img/icon4.png
  static/img/iconboy2.png
  static/styleRanqueamento.css
  templates/Ranqueamento.html
Labels: enhancement

#113 Coelhomca#93
  static/img/icon-2.png
  templates/avaliar-monitor.html
  templates/visualizar_demanda.html
Labels: enhancement

#114 Atualizando a API e conectando ao banco #102
  API/AjudaAiAPI/AjudaAiAPI.csproj
  API/AjudaAiAPI/Context/Comentario.cs
  API/AjudaAiAPI/Context/Demandum.cs
  API/AjudaAiAPI/Context/RailwayContext.cs
  API/AjudaAiAPI/Context/Usuario.cs
  API/AjudaAiAPI/Controllers/ComentariosController.cs
  API/AjudaAiAPI/Controllers/ConnectionController.cs
  API/AjudaAiAPI/Controllers/DemandasController.cs
  API/AjudaAiAPI/Controllers/UsuariosController.cs
Labels: enhancement

#116 Estilizando o botão de voltar de forma correta #115
  static/styleChatPrivado.css
Labels: bug

#117 Caiofeitosa7#103
  .gitignore
  facade.py
  model.py
  templates/avaliar-monitor.html
  templates/visualizar_demanda.html
  views.py
Labels: enhancement

#121 Caiofeitosa7#96
  facade.py
  model.py
  static/img/medalha.png
  static/img/procurar demandas.png
  templates/Ranqueamento.html
  templates/index.html
  templates/visualizar_demanda.html
  views.py
Labels: enhancement

#122 Tela aceitação de demanda incluída #94 .
  static/img/contribuicao.png
  static/style-visualizar-usuario.css
  templates/aceitar-demanda.html
Labels: enhancement

#126 Jaovctr#125
  .github/workflows/actions.yml
  templates/tests/PreencherDuvida.py
  templates/tests/test_cadastrodemanda.py
Labels: bug

#124 corrigndo os testes py #123
  templates/tests/PreencherDuvida.py
  templates/tests/test_cadastrodemanda.py
Labels: bug

#127 Caiofeitosa7#101
  facade.py
  model.py
  notifica_gestao.py
  views.py
Labels: enhancement

#128 Caiofeitosa7#92
  facade.py
  model.py
  templates/ChatPrivado.html
  templates/visualizar_demanda.html
  views.py
Labels: enhancement

#130 Concluida a funcionalidade de aceitar demanda. #129
  facade.py
  model.py
  static/styleChatPrivado.css
  templates/ChatPrivado.html
  templates/visualizar_demanda.html
  views.py
Labels: enhancement

#132 Let0210#131
  .github/workflows/actions.yml
  .gitignore
  .vscode/launch.json
  API/AjudaAiAPI/AjudaAiAPI.csproj
  API/AjudaAiAPI/Context/Comentario.cs
  API/AjudaAiAPI/Context/Demandum.cs
  API/AjudaAiAPI/Context/RailwayContext.cs
  API/AjudaAiAPI/Context/Usuario.cs
  API/AjudaAiAPI/Controllers/ComentariosController.cs
  API/AjudaAiAPI/Controllers/ConnectionController.cs
  API/AjudaAiAPI/Controllers/DemandumsController.cs
  API/AjudaAiAPI/Controllers/UsuariosController.cs
  BD/Diagrama 2.2.png
  BD/Diagrama ER AjudaAi.mwb
  BD/Diagrama ER AjudaAi.mwb.bak
  BD/Script.sql
  facade.py
  model.py
  static/img/contribuicao.png
  static/img/estrela.png
  static/img/icon-2.png
  static/img/icon3.png
  static/img/icon4.png
  static/img/iconboy2.png
  static/img/procurar demandas.png
  static/style-visualizar-usuario.css
  static/style.css
  static/styleRanqueamento.css
  templates/aceitar-demanda.html
  templates/avaliar-monitor.html
  templates/tests/chatPrivadoTeste.py
  templates/visualizar_demanda.html
  views.py
Labels: Tests

#134 Dev to main
  .github/workflows/actions.yml
  facade.py
  model.py
  notifica_gestao.py
  static/img/medalha.png
  static/styleChatPrivado.css
  templates/ChatPrivado.html
  templates/Ranqueamento.html
  templates/index.html
  templates/pagina_de_dados.html
  templates/tests/PreencherDuvida.py
  templates/tests/chatPrivadoTeste.py
  templates/tests/test_cadastrodemanda.py
  templates/visualizar_demanda.html
  views.py
Labels: enhancement
