Repository ES2-UFPI/AjudaAi, pull requests merged in 2023-02, with the labels that each got.

#28 Adicionando link na home pra lista de demandas Andisu07#9
  FrontEnd/HomePage/img/procurar demandas.png
  FrontEnd/HomePage/template/index.html
Labels: enhancement

#34 Jaovctr#11
  API/AjudaAiAPI/.config/dotnet-tools.json
  API/AjudaAiAPI/.dockerignore
  API/AjudaAiAPI/AjudaAiAPI - Backup.csproj
  API/AjudaAiAPI/AjudaAiAPI.csproj
  API/AjudaAiAPI/Controllers/AtreladumsController.cs
  API/AjudaAiAPI/Controllers/ConnectionController.cs
  API/AjudaAiAPI/Controllers/DemandumsController.cs
  API/AjudaAiAPI/Controllers/TagsController.cs
  API/AjudaAiAPI/Controllers/UsuariosController.cs
  API/AjudaAiAPI/Program.cs
  API/AjudaAiAPI/Properties/ServiceDependencies/AjudaAiAPI20230201195743 - Web Deploy/apis1.arm.json
  API/AjudaAiAPI/Properties/ServiceDependencies/AjudaAiAPI20230201195743 - Web Deploy/profile.arm.json
  API/AjudaAiAPI/Properties/serviceDependencies.AjudaAiAPI20230201195743 - Web Deploy.json
  API/AjudaAiAPI/Properties/serviceDependencies.json
Labels: enhancement

#26 Caiofeitosa7#24
  FrontEnd/HomePage/static/estilos.css
  FrontEnd/HomePage/template/index.html
  FrontEnd/cadastrar-demanda/README.md
  FrontEnd/cadastrar-demanda/index.html
  FrontEnd/cadastrar-demanda/src/images/favicon_transparent_32x32.ico
  FrontEnd/cadastrar-demanda/src/images/remove bg logo.png
  FrontEnd/minhas-demandas/README.md
  FrontEnd/minhas-demandas/index.html
  FrontEnd/minhas-demandas/src/images/favicon_transparent_32x32.ico
  FrontEnd/minhas-demandas/src/images/remove bg logo.png
  FrontEnd/visualizar-demanda/README.md
  FrontEnd/visualizar-demanda/src/css/reset.css
  FrontEnd/visualizar-demanda/src/images/Ufpi_brasão.png
  FrontEnd/visualizar-demanda/src/images/favicon_transparent_32x32.ico
  FrontEnd/visualizar-demanda/src/images/icon.png
  FrontEnd/visualizar-demanda/src/images/remove bg logo.png
  aplicacao.py
  facade.py
  model.py
  static/estilo_geral.css
  static/estilos_index.css
  static/img/Ufpi_brasão.png
  static/img/cadastro de demanda.png
  static/img/favicon_transparent_32x32.ico
  static/img/icon.png
  static/img/iconboy.png
  static/img/lista_geral.png
  static/img/lista_vector.png
  static/img/lixeira.png
  static/img/minhas_demandas.png
  static/img/pessoal estudando.png
  static/img/procurar demandas.png
  static/img/remove bg logo.png
  static/img/visualizar.png
  static/img/visualizar2.png
  static/resetVisualizarD1.css
  static/reset_demandas.css
  static/style.css
  static/styleVisualizarD1.css
  static/style_demandas.css
  templates/index.html
  templates/lista_demandas.html
  templates/login.html
  templates/minhas_demandas.html
  templates/visualizar_demanda1.html
  templates/visualizar_demanda2.html
  views.py
Labels: enhancement

#49 diagrama atualizado por eu Andisu07#38
  BD/Diagrama 2.0.png
  BD/Diagrama ER AjudaAi.mwb
  BD/Diagrama ER AjudaAi.mwb.bak
Labels: enhancement

#50 Let0210#43
  static/img/deslike.png
  static/img/icon2.png
  static/img/like.png
  static/styleTopicoForum.css
  templates/topicoForum.html
Labels: enhancement

#54 Corrigindo página para imagens aparecerem corretamente Let0210#53
  templates/topicoForum.html
Labels: bug

#55 Tela Visualizar Usuário #45.
  static/reset-visualizar-usuario.css
  static/style-visualizar-usuario.css
  templates/visualizar-usuario.html
Labels: enhancement

#52 diagrama atualizado Andisu07#51
  BD/Diagrama 2.1.png
Labels: bug

#56 Jaovctr#39
  BD/Script.sql
Labels: enhancement

#58 Caiofeitosa7#57
  facade.py
  model.py
  notifica.py
  templates/minhas_demandas.html
  templates/visualizar_demanda.html
  templates/visualizar_demanda1.html
  views.py
Labels: enhancement

#59 Disponibilizando o banco de dados na nuvem
  BD/conexao_banco.txt
  requirements.txt
Labels: Estrutura

#60 Let0210#41
  static/img/forum.png
  static/styleForum.css
  templates/Forum.html
  templates/index.html
Labels: enhancement

#66 Let0210#65
  templates/topicoForum.html
Labels: bug

#68 Let0210#67
  static/styleTopicoForum.css
  templates/topicoForum.html
Labels: bug

#71 atualizando lista de demandas Andisu07#69
  templates/lista_demandas.html
Labels: bug

#70 Jaovctr#64
  API/AjudaAiAPI/AjudaAiAPI.csproj
  API/AjudaAiAPI/Context/Comentario.cs
  API/AjudaAiAPI/Context/Forum.cs
  API/AjudaAiAPI/Context/RailwayContext.cs
  API/AjudaAiAPI/Context/Topico.cs
  API/AjudaAiAPI/Context/Usuario.cs
  API/AjudaAiAPI/Controllers/ComentariosController.cs
  API/AjudaAiAPI/Controllers/ForumController.cs
  API/AjudaAiAPI/Controllers/TopicosController.cs
Labels: enhancement

#73 Let0210#72
  templates/CadastrarDuvida.html
  templates/Forum.html
Labels: bug
