Repository ES2-UFPI/AjudaAi, pull requests merged in 2023-01, with the labels that each got.

#12 removendo fotos da wiki
  railway 1.png
  railway 2.png
  railway 3.png
  railway 4.png
  railway 5.png
Labels: documentation

#18 Diagrama da demanda criado. #3
  .gitignore
  DER/diagrama_demanda.png
Labels: enhancement

#20 Let0210#2
  FrontEnd/HomePage/img/Ufpi_brasão.png
  FrontEnd/HomePage/img/cadastro de demanda.png
  FrontEnd/HomePage/img/favicon_transparent_32x32.ico
  FrontEnd/HomePage/img/pessoal estudando.png
  FrontEnd/HomePage/img/remove bg logo.png
  FrontEnd/HomePage/static/estilos.css
  FrontEnd/HomePage/template/index.html
Labels: enhancement

#21 Andisu07#4
  BD/Diagrama ER AjudaAi.mwb
  BD/Diagrama ER AjudaAi.mwb.bak
  BD/Diagrama.png
  BD/Script.sql
  README.md
Labels: enhancement

#22 Instruções para conectar o banco #5
  BD/Instrucoes para conexao do banco.rar
Labels: enhancement

#23 Caiofeitosa7#3
  DER/DER_demanda.png
  DER/diagrama_demanda.png
Labels: bug

#25 Jaovctr#8
  .gitattributes
  .gitignore
  API/AjudaAiAPI/Adicionais/readme.md
  API/AjudaAiAPI/AjudaAiAPI - Backup.csproj
  API/AjudaAiAPI/AjudaAiAPI.csproj
  API/AjudaAiAPI/AjudaAiAPI.sln
  API/AjudaAiAPI/Context/Atreladum.cs
  API/AjudaAiAPI/Context/Demandum.cs
  API/AjudaAiAPI/Context/RailwayContext.cs
  API/AjudaAiAPI/Context/Tag.cs
  API/AjudaAiAPI/Context/Usuario.cs
  API/AjudaAiAPI/Controllers/AtreladumsController.cs
  API/AjudaAiAPI/Controllers/ConnectionController.cs
  API/AjudaAiAPI/Controllers/DemandumsController.cs
  API/AjudaAiAPI/Controllers/TagsController.cs
  API/AjudaAiAPI/Controllers/UsuariosController.cs
  API/AjudaAiAPI/Program.cs
  API/AjudaAiAPI/Properties/launchSettings.json
  API/AjudaAiAPI/appsettings.Development.json
  API/AjudaAiAPI/appsettings.json
Labels: enhancement
